language: node_js
services:
  - memcached
  - redis-server

env:
  - SENECA_VER=senecajs/seneca
  - SENECA_VER=plugin

node_js:
  - "10"
  - "12"
  - "13"
  - "14"


before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls

